### ISSUE TITLE
Design a prettier icon

### ISSUE THREAD

**Issue by micahflee** [micahflee/porcupine#2]

**Comment by KyleRConway** [comment]
Thoughts?

![selection_263](https://cloud.githubusercontent.com/assets/5899012/25033734/1bd0b9c8-20a6-11e7-96d1-19204797a958.png)

**Comment by micahflee** [comment]
Ooh, nice. The icon needs to be square (or circular), so I don't think the top-left ones will work. I think out of these my favorite is the bottom-right one.

I was also invisioning a roundish cartoon porcupine, basically with lots of spikes on its back and head, but with no text. So it's not what I had in mind, but already it's much nicer than the temporary one I'm using.

**Comment by KyleRConway** [comment]
Something cuter than this then (!)

![selection_264](https://cloud.githubusercontent.com/assets/5899012/25052935/06b14bec-211a-11e7-9548-b0fa3df9dfa2.png)

**Comment by KyleRConway** [comment]
Playing... 
![selection_265](https://cloud.githubusercontent.com/assets/5899012/25054544/4d89583a-2123-11e7-810e-bdade68d6018.png)

**Comment by anxiousnix** [comment]
Something simple, yet Firefox-esque would be great.

**Comment by KyleRConway** [comment]
Playing again (after apparently a year!)


![porcupine](https://user-images.githubusercontent.com/5899012/38328870-a3504c50-3811-11e8-9de8-5084db395150.png)

**Comment by anxiousnix** [comment]
This icon does feel a bit more approachable for sure! Also pretty cute. :)

**Comment by micahflee** [comment]
Thanks @KyleRConway, this is awesome. I like it.

**Comment by KyleRConway** [comment]
Thanks! I still think it can be improved upon. Do you have any specific 
colors in mind? Also, I was thinking about flattening the shapes (right 
now the underlying elements (e.g. circles) are somewhat transparent. 
Time does fly!
