### ISSUE TITLE
Qubes integration

### ISSUE THREAD

**Issue by tabbyrobin** [micahflee/porcupine#4]
Porcupine seems like a perfect candidate for integration into Qubes OS. 

The use cases intersect with many of the issues described in your blog post:
https://micahflee.com/2016/06/qubes-tip-opening-links-in-your-preferred-appvm/

Related, I know there's also been some work on Qubes MIME Handlers (GSoC project):
https://groups.google.com/forum/#!searchin/qubes-devel/Qubes-MIME-Handlers%7Csort:date/qubes-devel/B8QJueAZcYA/pSNzIKeeCgAJ

**Comment by micahflee** [comment]
I think all that really needs to happen for Purcupine to be integrated into Qubes is for it to get packaged in Fedora (and possibly also Debian). I bet this is doable. Once it's packaged, the steps to integrate this to Qubes would be:

- Install Porcupine in your TemplateVM
- Set it as the default browser
- Power off your template

Then all new AppVMs you create will open links in Porcupine. And you can manually set Porcupine as your default browser in existing AppVMs.

**Comment by micahflee** [comment]
Porcupine is now is fedora, so I think basically makes Qubes integration "done":

```sh
$ dnf search porcupine
Last metadata expiration check: 1 day, 2:14:12 ago on Mon 30 Apr 2018 05:05:08 PM PDT.
============================================================================== Summary & Name Matched: porcupine ==============================================================================
porcupine.noarch : Set porcupine as your default web browser. When you click a link, porcupine will copy the URL to your clipboard and notify you about this.
```
