### ISSUE TITLE
Update desktop file and icon

### ISSUE THREAD

**Issue by micahflee** [micahflee/porcupine#8]
From Fedora package review: https://taskotron.fedoraproject.org/artifacts/all/28b2a0b4-4267-11e8-8c0e-525400fc9f92/tests.yml/rpmgrill.json

```
    {
         "module" : "DesktopLint",
         "order" : 93,
         "results" : [
            {
               "arch" : "noarch",
               "code" : "DesktopFileValidation",
               "context" : {
                  "path" : "/usr/share/applications/porcupine.desktop"
               },
               "diag" : "warning: key \"Encoding\" in group \"Desktop Entry\" is deprecated",
               "subpackage" : "porcupine"
            },
            {
               "arch" : "noarch",
               "code" : "DesktopFileValidation",
               "context" : {
                  "path" : "/usr/share/applications/porcupine.desktop"
               },
               "diag" : "error: (will be fatal in the future): value \"porcupine.png\" for key \"Icon\" in group \"Desktop Entry\" is an icon name with an extension, but there should be no extension as described in the Icon Theme Specification if the value is not an absolute path",
               "subpackage" : "porcupine"
            }
         ],
         "run_time" : 0,
         "status" : "completed"
      }
```

**Comment by anxiousnix** [comment]
In Debian, running `desktop-file-validate` (part of the `desktop-file-utils` package), shows the following output, which is reflected above:
>porcupine.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
>porcupine.desktop: error: (will be fatal in the future): value "porcupine.png" for key "Icon" in group "Desktop Entry" is an icon name with an extension, but there should be no extension as described in the Icon Theme Specification if the value is not an absolute path
Probably a simple fix. Let me see what I can whip up.
